### ISSUE TITLE
找不到basicsr.utils

### ISSUE THREAD

**Issue by 634085586** [icandle/CAMixerSR#20]
尝试使用Readme中的文件运行然后报错了
code/basicsr文件夹下并没有utils诶

Traceback (most recent call last):
  File "/mnt/CAMixerSR/codes/basicsr/test.py", line 4, in <module>
    import archs
  File "/mnt/CAMixerSR/codes/basicsr/archs/__init__.py", line 5, in <module>
    from basicsr.utils import get_root_logger, scandir
ModuleNotFoundError: No module named 'basicsr'

**Comment by icandle** [comment]
因为这个项目依赖于[basicsr](https://github.com/XPixelGroup/BasicSR/blob/master/docs/INSTALL.md)这个包，需要先安装它
```
pip install basicsr
```

**Comment by 634085586** [comment]
哦哦了解了 感谢～
